language: python
sudo: required

python:
    - "2.7"

install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt
    # libsodium install
    - git clone https://github.com/jedisct1/libsodium.git libsodium
    - cd libsodium
    - git checkout tags/1.0.3 > /dev/null
    - ./autogen.sh > /dev/null
    - ./configure > /dev/null
    - make check -j2 || make check || exit 1 > /dev/null
    - sudo make install > /dev/null
    - sudo ldconfig
    - cd ..

script:
    - cd keyutils
    - python setup.py install
    - cd ..
    - make -s

after_success:
    - coveralls
