language: python

python:
    - "2.7"

install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install -r test_requirements.txt

script:
    - python keyutils/setup.py install
    - make -s

after_success:
    - coveralls
